from pydantic import BaseModel as BaseModel
from typing import Iterable, Optional, Type

def set_title(title: str): ...
def set_doc(doc: str): ...
def set_discriminator(discriminator: str): ...
def add_multi_type_field(field_name: str, types: Iterable[Type[BaseModel]], discriminator: Optional[str] = ..., field_title: str = ..., field_doc: str = ...): ...
