# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-08-20 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_task",
            "0002_task_eta_task_expires_task_is_eager_task_retries_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table="background_task",
        ),
    ]
