# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class OrmWithdrawHistoryOrganizationEdges(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'organizations': 'OrmOrganization',
        'transferee': 'OrmUser',
        'user_history': 'OrmUserHistory'
    }

    attribute_map = {
        'organizations': 'organizations',
        'transferee': 'transferee',
        'user_history': 'user_history'
    }

    def __init__(self, organizations=None, transferee=None, user_history=None, local_vars_configuration=None):  # noqa: E501
        """OrmWithdrawHistoryOrganizationEdges - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._organizations = None
        self._transferee = None
        self._user_history = None
        self.discriminator = None

        if organizations is not None:
            self.organizations = organizations
        if transferee is not None:
            self.transferee = transferee
        if user_history is not None:
            self.user_history = user_history

    @property
    def organizations(self):
        """Gets the organizations of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501


        :return: The organizations of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501
        :rtype: OrmOrganization
        """
        return self._organizations

    @organizations.setter
    def organizations(self, organizations):
        """Sets the organizations of this OrmWithdrawHistoryOrganizationEdges.


        :param organizations: The organizations of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501
        :type organizations: OrmOrganization
        """

        self._organizations = organizations

    @property
    def transferee(self):
        """Gets the transferee of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501


        :return: The transferee of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501
        :rtype: OrmUser
        """
        return self._transferee

    @transferee.setter
    def transferee(self, transferee):
        """Sets the transferee of this OrmWithdrawHistoryOrganizationEdges.


        :param transferee: The transferee of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501
        :type transferee: OrmUser
        """

        self._transferee = transferee

    @property
    def user_history(self):
        """Gets the user_history of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501


        :return: The user_history of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501
        :rtype: OrmUserHistory
        """
        return self._user_history

    @user_history.setter
    def user_history(self, user_history):
        """Sets the user_history of this OrmWithdrawHistoryOrganizationEdges.


        :param user_history: The user_history of this OrmWithdrawHistoryOrganizationEdges.  # noqa: E501
        :type user_history: OrmUserHistory
        """

        self._user_history = user_history

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrmWithdrawHistoryOrganizationEdges):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrmWithdrawHistoryOrganizationEdges):
            return True

        return self.to_dict() != other.to_dict()
