issues = [
    "billing issue",
    "account issue",
    "software issue",
    "app issue",
    "hardware issue",
    "network issue",
    "configuration issue",
    "screen issue",
    "sound issue",
    "multi-touch issue",
    "button issue",
    "microphone issue",
    "siri issue",
    "apple pay issue",
    "nfc issue",
    "camera issue",
    "icloud issue",
    "sync issue",
    "sales issue",
    "problem",
    "issue",
    "bad experience",
    "poor quality",
    "hidden defect",
    "repair issue"
]

devices = [
    "iphone 14 pro max",
    "iphone 14 pro",
    "iphone 14",
    "iphone 13 pro max",
    "iphone 13 pro",
    "iphone 13",
    "iphone 13 mini",
    "iphone 12 pro max",
    "iphone 12 pro",
    "iphone 12",
    "iphone 12 mini",
    "iphone se",
    "ipad",
    "ipad mini"
    "ipad air"
    "ipad pro"
    "macbook pro",
    "mackbook air",
    "imac",
    "mac pro",
    "airpods 2nd generation",
    "airpods 3nd generation",
    "airpods pro 1st generation",
    "airpods pro 2nd generation",
    "airpods pro max",
    "homepod mini",
    "homepod",
    "apple tv",
    "apple watch ultra",
    "apple watch serie 8",
    "apple watch se",
    "studio display",
    "pro display xdr",
]

positive_sequences = [
    "The agent was incredibly helpful.",
    "Quick and efficient service!",
    "Solved my problem right away.",
    "Friendly and professional interaction.",
    "Went above and beyond to assist me.",
    "I'm really satisfied with the support I received.",
    "The representative made everything clear and simple.",
    "Great experience! I felt listened to.",
    "I appreciate the timely response and resolution.",
    "The support team was very attentive to my needs.",
    "Exceptional service from a knowledgeable agent.",
    "I was treated with respect and empathy.",
    "Everything was handled with care and precision.",
    "The agent's expertise really shone through.",
    "I felt like a valued customer.",
    "The support exceeded my expectations.",
    "They made sure I understood everything.",
    "I was pleasantly surprised by the dedication of the team.",
    "The agent took the time to understand my situation.",
    "Thank you for making a complex issue seem simple.",
    "The customer support was exceptional, resolving my issue in no time.",
    "I was amazed by the professionalism and kindness of the support team.",
    "The representative went the extra mile to make sure I was satisfied.",
    "Their expertise and attentiveness made the process smooth and enjoyable.",
    "Prompt service with a smile, I couldn't have asked for more!",
    "The agent's patience and understanding made me feel at ease.",
    "I appreciate the clear communication and quick resolution of my problem.",
    "The support I received was top-notch; I'm a happy customer!",
    "They handled my concern with grace and efficiency, leaving me impressed.",
    "I felt valued and well-taken care of by the support team.",
    "The assistance I received was beyond my expectations, truly remarkable service!",
    "I'm grateful for the friendly and competent support that resolved my issue quickly.",
    "The agent's dedication to helping me was evident, and I'm very satisfied.",
    "Their responsiveness and attention to detail made all the difference.",
    "A wonderful experience from start to finish; I'll definitely recommend their services.",
    "The support team was not only knowledgeable but also incredibly personable."
]

neutral_sequences = [
    "The call was okay.",
    "Service was as expected.",
    "I got what I needed.",
    "Neither good nor bad; it was fine.",
    "Typical call center experience.",
    "The agent did what was required.",
    "Nothing special, but my issue was resolved.",
    "The call was neither pleasant nor unpleasant.",
    "It was just a standard support call.",
    "I didn't have any problems, but nothing stood out.",
    "The support was adequate.",
    "Everything went as I anticipated.",
    "No complaints, but also no compliments.",
    "The service was functional and basic.",
    "The agent was professional but not particularly engaging.",
    "I got the information I needed, nothing more or less.",
    "It was a routine support experience.",
    "The process was straightforward but not memorable.",
    "I don't have strong feelings about the experience.",
    "The call was handled in a usual manner.",
    "the service was fine, but nothing special.",
    "I received the help I needed, but it took longer than expected.",
    "the agent was polite, but didn't seem very knowledgeable.",
    "the issue was resolved, but the process was more complicated than it needed to be.",
    "I got the support I needed, but the overall experience was just okay.",
    "the service was adequate, but not particularly memorable.",
    "the agent helped me, but the solution took some time to implement.",
    "I was assisted with my problem, but the response time could have been better.",
    "the support was acceptable, but lacked a personal touch.",
    "my issue was addressed, but the agent seemed distracted.",
    "the help I received was satisfactory, but I've had better experiences before.",
    "the support was decent, but it didn't exceed my expectations.",
    "I was helped with my issue, but the process was rather tedious.",
    "the agent resolved my problem, but the communication could have been clearer.",
    "I received support, but it was a pretty standard experience.",
    "the service was functional, but not very engaging.",
    "my issue was handled, but the solution was only temporary.",
    "the support was competent, but lacked enthusiasm.",
    "I got the help I needed, but there was room for improvement.",
    "the assistance was okay, but I've had more efficient support in the past."
]

negative_sequences = [
    "I was on hold forever.",
    "The agent was rude and unhelpful.",
    "Didn't resolve my issue at all.",
    "Misinformation provided; I'm frustrated.",
    "No follow-through on promises made.",
    "The support was confusing and slow.",
    "I felt ignored and unimportant.",
    "The agent seemed uninterested in helping me.",
    "I'm very dissatisfied with the service I received.",
    "The call made my problem even worse.",
    "I had to repeat myself multiple times.",
    "The agent kept interrupting me.",
    "I was passed around without any resolution.",
    "Terrible experience; I'm very disappointed.",
    "The support team seemed uninformed and careless.",
    "I never received the follow-up I was promised.",
    "The agent was condescending and impatient.",
    "I wasted a lot of time without getting help.",
    "The whole process was frustrating and unprofessional.",
    "I was left feeling more confused than before.",
    "the service was slow and unresponsive.",
    "I was left unsatisfied with the support I received.",
    "the agent seemed uninterested in helping me.",
    "my issue was never fully resolved.",
    "I felt like I was just a number, not a valued customer.",
    "the support was confusing and lacked clarity.",
    "I was passed around between agents without a resolution.",
    "the response time was unacceptable, and my issue lingered.",
    "I felt ignored and unimportant during the process.",
    "the solution provided was temporary and didn't fix the underlying problem.",
    "I was frustrated by the lack of expertise shown by the support team.",
    "the agent was rude and seemed bothered by my questions.",
    "I had to repeat myself multiple times, and my issue was still not fixed.",
    "the support was impersonal and lacked empathy.",
    "I was promised a solution, but it never materialized.",
    "the handling of my issue was careless and unprofessional.",
    "I spent a long time on hold, only to receive inadequate support.",
    "the agent's lack of knowledge made the situation worse.",
    "I felt more confused after the support than before.",
    "the entire experience was disappointing and left me frustrated.",
    "I had to contact support multiple times without a satisfactory resolution.",
    "the agent seemed to rush through the process without fully understanding my problem.",
    "I was given incorrect information that complicated my situation.",
    "the lack of follow-through made me feel neglected and unimportant.",
    "I was met with indifference and a lack of effort to truly resolve my issue."
]

positive_templates = [
    "I called about my {device} having {issue}, and {positive_sequence}.",
    "My experience with {device} {issue} was great because {positive_sequence}.",
    "Regarding the {issue} with my {device}, {positive_sequence}.",
    "I had an {issue} with my {device}, but the support team was amazing: {positive_sequence}.",
    "The agent helped me with my {device}'s {issue} and {positive_sequence}.",
    "I reached out for support with my {device} and {issue}, and {positive_sequence}.",
    "My {device} had an {issue}, but the help I received was excellent: {positive_sequence}.",
    "I needed assistance with my {device}'s {issue}, and {positive_sequence}.",
    "The {issue} on my {device} was quickly handled; {positive_sequence}.",
    "I spoke with an agent about my {device}'s {issue}, and {positive_sequence}.",
    "I was experiencing {issue} with my {device}, but {positive_sequence}.",
    "I contacted support for my {device} {issue}, and {positive_sequence}.",
    "I was worried about my {device}'s {issue}, but the agent {positive_sequence}.",
    "I had a concern about {issue} on my {device}, and the response was great: {positive_sequence}.",
    "I required support for {issue} with my {device}, and {positive_sequence}.",
    "I encountered {issue} with my {device}, but the support was outstanding: {positive_sequence}.",
    "My {device} was facing {issue}, but the agent's assistance was excellent: {positive_sequence}.",
    "I reached out regarding {issue} on my {device}, and {positive_sequence}.",
    "I needed help with my {device}'s {issue}, and the agent's response was: {positive_sequence}.",
    "My call was about {issue} with my {device}, and {positive_sequence}.",
    "When I encountered {issue} with my {device}, the support team was there to help: {positive_sequence}.",
    "I had a question about {issue} on my {device}, and the support team was fantastic: {positive_sequence}.",
    "The {issue} with my {device} was concerning, but the assistance I received was top-notch: {positive_sequence}.",
    "I was struggling with {issue} on my {device}, but the prompt support made all the difference: {positive_sequence}.",
    "I called for help with my {device}'s {issue}, and I was impressed by the service: {positive_sequence}.",
    "My {device} was having {issue}, but the support team turned it into a positive experience: {positive_sequence}.",
    "I reached out about the {issue} on my {device}, and I couldn't be happier with the support: {positive_sequence}.",
    "The {issue} with my {device} seemed daunting, but the agent's help was incredible: {positive_sequence}.",
    "I was facing {issue} with my {device}, but the support I received was exemplary: {positive_sequence}.",
    "My {device} had a {issue}, but the assistance from the support team was outstanding: {positive_sequence}.",
    "I had concerns about {issue} on my {device}, but the agent's support put me at ease: {positive_sequence}.",
    "I was dealing with {issue} on my {device}, but the agent's expertise made it simple: {positive_sequence}.",
    "I contacted support about my {device}'s {issue}, and I was thrilled with the response: {positive_sequence}.",
    "The {issue} with my {device} was frustrating, but the support team was patient and helpful: {positive_sequence}.",
    "I needed guidance with {issue} on my {device}, and the support team was exceptional: {positive_sequence}.",
    "I was puzzled by {issue} with my {device}, but the agent's clarity and help were superb: {positive_sequence}.",
    "I had trouble with {issue} on my {device}, but the support I received was first-rate: {positive_sequence}.",
    "The {issue} on my {device} was resolved with professionalism and care: {positive_sequence}.",
    "I was distressed by {issue} on my {device}, but the support team's empathy made it better: {positive_sequence}.",
    "My {device} was having {issue}, but the quick and attentive support made it right: {positive_sequence}."
]

neutral_templates = [
    "I called about my {device} having {issue}, and {neutral_sequence}.",
    "Regarding the {issue} with my {device}, {neutral_sequence}.",
    "I had an {issue} with my {device}, and the support was okay: {neutral_sequence}.",
    "The agent assisted me with my {device}'s {issue}, and {neutral_sequence}.",
    "I reached out for help with my {device} and {issue}, and {neutral_sequence}.",
    "My {device} had an {issue}, and the help I received was adequate: {neutral_sequence}.",
    "I needed assistance with my {device}'s {issue}, and {neutral_sequence}.",
    "The {issue} on my {device} was handled, but {neutral_sequence}.",
    "I spoke with an agent about my {device}'s {issue}, and {neutral_sequence}.",
    "I was experiencing {issue} with my {device}, and {neutral_sequence}.",
    "I contacted support for my {device} {issue}, and {neutral_sequence}.",
    "I was concerned about my {device}'s {issue}, and the agent {neutral_sequence}.",
    "I had a question about {issue} on my {device}, and the response was: {neutral_sequence}.",
    "I required support for {issue} with my {device}, and {neutral_sequence}.",
    "I encountered {issue} with my {device}, and the support was just okay: {neutral_sequence}.",
    "My {device} was having {issue}, and the agent's assistance was standard: {neutral_sequence}.",
    "I reached out regarding {issue} on my {device}, and {neutral_sequence}.",
    "I needed help with my {device}'s {issue}, and the agent's response was: {neutral_sequence}.",
    "My call was about {issue} with my {device}, and {neutral_sequence}.",
    "I had a problem with {issue} on my {device}, and the service was typical: {neutral_sequence}.",
    "I called about {issue} with my {device}, and {neutral_sequence}.",
    "I had an {issue} with my {device}, and the support team's response was: {neutral_sequence}.",
    "Regarding the {issue} with my {device}, the support was {neutral_sequence}.",
    "I reached out for help with my {device}'s {issue}, and the experience was {neutral_sequence}.",
    "The agent assisted me with {issue} on my {device}, and the service was {neutral_sequence}.",
    "I contacted support about {issue} with my {device}, and the response was {neutral_sequence}.",
    "I was experiencing {issue} on my {device}, and the support was {neutral_sequence}.",
    "I needed help with my {device}'s {issue}, and the agent's assistance was {neutral_sequence}.",
    "The {issue} with my {device} was handled, and the overall experience was {neutral_sequence}.",
    "I spoke to an agent about {issue} on my {device}, and the support was {neutral_sequence}.",
    "I reached out regarding {issue} with my {device}, and the service was {neutral_sequence}.",
    "My {device} had a {issue}, and the support I received was {neutral_sequence}.",
    "I was concerned about {issue} on my {device}, and the support was {neutral_sequence}.",
    "I had questions about {issue} with my {device}, and the response was {neutral_sequence}.",
    "I encountered {issue} with my {device}, and the support was adequate: {neutral_sequence}.",
    "I required assistance with {issue} on my {device}, and the experience was {neutral_sequence}.",
    "My {device} was facing {issue}, and the support was reasonable: {neutral_sequence}.",
    "I needed guidance on {issue} with my {device}, and the support was {neutral_sequence}.",
    "I was dealing with {issue} on my {device}, and the support was satisfactory: {neutral_sequence}.",
    "I was troubled by {issue} with my {device}, but the support was acceptable: {neutral_sequence}."
]

negative_templates = [
    "I called about my {device} having {issue}, and {negative_sequence}.",
    "Regarding the {issue} with my {device}, {negative_sequence}.",
    "I had an {issue} with my {device}, and the support was terrible: {negative_sequence}.",
    "The agent failed to help me with my {device}'s {issue}, and {negative_sequence}.",
    "I reached out for help with my {device} and {issue}, and {negative_sequence}.",
    "My {device} had an {issue}, and the help I received was unsatisfactory: {negative_sequence}.",
    "I needed assistance with my {device}'s {issue}, and {negative_sequence}.",
    "The {issue} on my {device} was mishandled, and {negative_sequence}.",
    "I spoke with an agent about my {device}'s {issue}, and {negative_sequence}.",
    "I was experiencing {issue} with my {device}, and {negative_sequence}.",
    "I contacted support for my {device} {issue}, and {negative_sequence}.",
    "I was upset about my {device}'s {issue}, and the agent {negative_sequence}.",
    "I had a major problem with {issue} on my {device}, and the response was: {negative_sequence}.",
    "I required support for {issue} with my {device}, and {negative_sequence}.",
    "I encountered {issue} with my {device}, and the support was frustrating: {negative_sequence}.",
    "My {device} was having {issue}, and the agent's assistance was terrible: {negative_sequence}.",
    "I reached out regarding {issue} on my {device}, and {negative_sequence}.",
    "I needed help with my {device}'s {issue}, and the agent's response was: {negative_sequence}.",
    "My call was about {issue} with my {device}, and {negative_sequence}.",
    "I had a horrible experience with {issue} on my {device}, and the service was: {negative_sequence}.",
    "I called about {issue} with my {device}, and {negative_sequence}.",
    "I had an {issue} with my {device}, and the support team's response was: {negative_sequence}.",
    "Regarding the {issue} with my {device}, the support was {negative_sequence}.",
    "I reached out for help with my {device}'s {issue}, and the experience was {negative_sequence}.",
    "The agent assisted me with {issue} on my {device}, and the service was {negative_sequence}.",
    "I contacted support about {issue} with my {device}, and the response was {negative_sequence}.",
    "I was experiencing {issue} on my {device}, and the support was {negative_sequence}.",
    "I needed help with my {device}'s {issue}, and the agent's assistance was {negative_sequence}.",
    "The {issue} with my {device} was handled, and the overall experience was {negative_sequence}.",
    "I spoke to an agent about {issue} on my {device}, and the support was {negative_sequence}.",
    "I reached out regarding {issue} with my {device}, and the service was {negative_sequence}.",
    "My {device} had a {issue}, and the support I received was {negative_sequence}.",
    "I was concerned about {issue} on my {device}, and the support was {negative_sequence}.",
    "I had questions about {issue} with my {device}, and the response was {negative_sequence}.",
    "I encountered {issue} with my {device}, and the support was disappointing: {negative_sequence}.",
    "I required assistance with {issue} on my {device}, and the experience was {negative_sequence}.",
    "My {device} was facing {issue}, and the support was frustrating: {negative_sequence}.",
    "I needed guidance on {issue} with my {device}, and the support was {negative_sequence}.",
    "I was dealing with {issue} on my {device}, and the support was unsatisfactory: {negative_sequence}.",
    "I was troubled by {issue} with my {device}, but the support was unacceptable: {negative_sequence}."
]
