# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/moderation/v1beta1/moderation_api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from speechly.moderation.v1beta1 import moderation_pb2 as speechly_dot_moderation_dot_v1beta1_dot_moderation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='speechly/moderation/v1beta1/moderation_api.proto',
  package='speechly.moderation.v1beta1',
  syntax='proto3',
  serialized_options=b'\n\037com.speechly.moderation.v1beta1B\022ModerationApiProtoP\001Z&speechly/moderation/v1beta1;sluv1beta1\242\002\003SMX\252\002\033Speechly.Moderation.V1Beta1\312\002\033Speechly\\Moderation\\V1Beta1',
  serialized_pb=b'\n0speechly/moderation/v1beta1/moderation_api.proto\x12\x1bspeechly.moderation.v1beta1\x1a,speechly/moderation/v1beta1/moderation.proto\"\xb2\x01\n\x15TextModerationRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12H\n\x11\x64iscourse_context\x18\x03 \x01(\x0b\x32-.speechly.moderation.v1beta1.DiscourseContext\x12\x15\n\rlanguage_code\x18\x04 \x01(\t\x12\x18\n\x10\x61udio_context_id\x18\x05 \x01(\t\"V\n\x16TextModerationResponse\x12<\n\x06labels\x18\x01 \x03(\x0b\x32,.speechly.moderation.v1beta1.ModerationLabel\"\x84\x01\n\x16\x41udioModerationRequest\x12\x44\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x32.speechly.moderation.v1beta1.AudioModerationConfigH\x00\x12\x0f\n\x05\x61udio\x18\x02 \x01(\x0cH\x00\x42\x13\n\x11streaming_request\"[\n\x17\x41udioModerationResponse\x12@\n\x08segments\x18\x01 \x03(\x0b\x32..speechly.moderation.v1beta1.ModerationSegment\"\x8d\x01\n\x1fStreamingAudioModerationRequest\x12\x44\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x32.speechly.moderation.v1beta1.AudioModerationConfigH\x00\x12\x0f\n\x05\x61udio\x18\x02 \x01(\x0cH\x00\x42\x13\n\x11streaming_request\"c\n StreamingAudioModerationResponse\x12?\n\x07segment\x18\x01 \x01(\x0b\x32..speechly.moderation.v1beta1.ModerationSegment2\xa8\x03\n\rModerationAPI\x12~\n\x0f\x41udioModeration\x12\x33.speechly.moderation.v1beta1.AudioModerationRequest\x1a\x34.speechly.moderation.v1beta1.AudioModerationResponse(\x01\x12\x9b\x01\n\x18StreamingAudioModeration\x12<.speechly.moderation.v1beta1.StreamingAudioModerationRequest\x1a=.speechly.moderation.v1beta1.StreamingAudioModerationResponse(\x01\x30\x01\x12y\n\x0eTextModeration\x12\x32.speechly.moderation.v1beta1.TextModerationRequest\x1a\x33.speechly.moderation.v1beta1.TextModerationResponseB\xa1\x01\n\x1f\x63om.speechly.moderation.v1beta1B\x12ModerationApiProtoP\x01Z&speechly/moderation/v1beta1;sluv1beta1\xa2\x02\x03SMX\xaa\x02\x1bSpeechly.Moderation.V1Beta1\xca\x02\x1bSpeechly\\Moderation\\V1Beta1b\x06proto3'
  ,
  dependencies=[speechly_dot_moderation_dot_v1beta1_dot_moderation__pb2.DESCRIPTOR,])




_TEXTMODERATIONREQUEST = _descriptor.Descriptor(
  name='TextModerationRequest',
  full_name='speechly.moderation.v1beta1.TextModerationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='speechly.moderation.v1beta1.TextModerationRequest.model_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='speechly.moderation.v1beta1.TextModerationRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discourse_context', full_name='speechly.moderation.v1beta1.TextModerationRequest.discourse_context', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language_code', full_name='speechly.moderation.v1beta1.TextModerationRequest.language_code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_context_id', full_name='speechly.moderation.v1beta1.TextModerationRequest.audio_context_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=306,
)


_TEXTMODERATIONRESPONSE = _descriptor.Descriptor(
  name='TextModerationResponse',
  full_name='speechly.moderation.v1beta1.TextModerationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='speechly.moderation.v1beta1.TextModerationResponse.labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=394,
)


_AUDIOMODERATIONREQUEST = _descriptor.Descriptor(
  name='AudioModerationRequest',
  full_name='speechly.moderation.v1beta1.AudioModerationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='speechly.moderation.v1beta1.AudioModerationRequest.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='speechly.moderation.v1beta1.AudioModerationRequest.audio', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='streaming_request', full_name='speechly.moderation.v1beta1.AudioModerationRequest.streaming_request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=397,
  serialized_end=529,
)


_AUDIOMODERATIONRESPONSE = _descriptor.Descriptor(
  name='AudioModerationResponse',
  full_name='speechly.moderation.v1beta1.AudioModerationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segments', full_name='speechly.moderation.v1beta1.AudioModerationResponse.segments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=622,
)


_STREAMINGAUDIOMODERATIONREQUEST = _descriptor.Descriptor(
  name='StreamingAudioModerationRequest',
  full_name='speechly.moderation.v1beta1.StreamingAudioModerationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='speechly.moderation.v1beta1.StreamingAudioModerationRequest.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='speechly.moderation.v1beta1.StreamingAudioModerationRequest.audio', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='streaming_request', full_name='speechly.moderation.v1beta1.StreamingAudioModerationRequest.streaming_request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=625,
  serialized_end=766,
)


_STREAMINGAUDIOMODERATIONRESPONSE = _descriptor.Descriptor(
  name='StreamingAudioModerationResponse',
  full_name='speechly.moderation.v1beta1.StreamingAudioModerationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='speechly.moderation.v1beta1.StreamingAudioModerationResponse.segment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=768,
  serialized_end=867,
)

_TEXTMODERATIONREQUEST.fields_by_name['discourse_context'].message_type = speechly_dot_moderation_dot_v1beta1_dot_moderation__pb2._DISCOURSECONTEXT
_TEXTMODERATIONRESPONSE.fields_by_name['labels'].message_type = speechly_dot_moderation_dot_v1beta1_dot_moderation__pb2._MODERATIONLABEL
_AUDIOMODERATIONREQUEST.fields_by_name['config'].message_type = speechly_dot_moderation_dot_v1beta1_dot_moderation__pb2._AUDIOMODERATIONCONFIG
_AUDIOMODERATIONREQUEST.oneofs_by_name['streaming_request'].fields.append(
  _AUDIOMODERATIONREQUEST.fields_by_name['config'])
_AUDIOMODERATIONREQUEST.fields_by_name['config'].containing_oneof = _AUDIOMODERATIONREQUEST.oneofs_by_name['streaming_request']
_AUDIOMODERATIONREQUEST.oneofs_by_name['streaming_request'].fields.append(
  _AUDIOMODERATIONREQUEST.fields_by_name['audio'])
_AUDIOMODERATIONREQUEST.fields_by_name['audio'].containing_oneof = _AUDIOMODERATIONREQUEST.oneofs_by_name['streaming_request']
_AUDIOMODERATIONRESPONSE.fields_by_name['segments'].message_type = speechly_dot_moderation_dot_v1beta1_dot_moderation__pb2._MODERATIONSEGMENT
_STREAMINGAUDIOMODERATIONREQUEST.fields_by_name['config'].message_type = speechly_dot_moderation_dot_v1beta1_dot_moderation__pb2._AUDIOMODERATIONCONFIG
_STREAMINGAUDIOMODERATIONREQUEST.oneofs_by_name['streaming_request'].fields.append(
  _STREAMINGAUDIOMODERATIONREQUEST.fields_by_name['config'])
_STREAMINGAUDIOMODERATIONREQUEST.fields_by_name['config'].containing_oneof = _STREAMINGAUDIOMODERATIONREQUEST.oneofs_by_name['streaming_request']
_STREAMINGAUDIOMODERATIONREQUEST.oneofs_by_name['streaming_request'].fields.append(
  _STREAMINGAUDIOMODERATIONREQUEST.fields_by_name['audio'])
_STREAMINGAUDIOMODERATIONREQUEST.fields_by_name['audio'].containing_oneof = _STREAMINGAUDIOMODERATIONREQUEST.oneofs_by_name['streaming_request']
_STREAMINGAUDIOMODERATIONRESPONSE.fields_by_name['segment'].message_type = speechly_dot_moderation_dot_v1beta1_dot_moderation__pb2._MODERATIONSEGMENT
DESCRIPTOR.message_types_by_name['TextModerationRequest'] = _TEXTMODERATIONREQUEST
DESCRIPTOR.message_types_by_name['TextModerationResponse'] = _TEXTMODERATIONRESPONSE
DESCRIPTOR.message_types_by_name['AudioModerationRequest'] = _AUDIOMODERATIONREQUEST
DESCRIPTOR.message_types_by_name['AudioModerationResponse'] = _AUDIOMODERATIONRESPONSE
DESCRIPTOR.message_types_by_name['StreamingAudioModerationRequest'] = _STREAMINGAUDIOMODERATIONREQUEST
DESCRIPTOR.message_types_by_name['StreamingAudioModerationResponse'] = _STREAMINGAUDIOMODERATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextModerationRequest = _reflection.GeneratedProtocolMessageType('TextModerationRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTMODERATIONREQUEST,
  '__module__' : 'speechly.moderation.v1beta1.moderation_api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.moderation.v1beta1.TextModerationRequest)
  })
_sym_db.RegisterMessage(TextModerationRequest)

TextModerationResponse = _reflection.GeneratedProtocolMessageType('TextModerationResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEXTMODERATIONRESPONSE,
  '__module__' : 'speechly.moderation.v1beta1.moderation_api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.moderation.v1beta1.TextModerationResponse)
  })
_sym_db.RegisterMessage(TextModerationResponse)

AudioModerationRequest = _reflection.GeneratedProtocolMessageType('AudioModerationRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOMODERATIONREQUEST,
  '__module__' : 'speechly.moderation.v1beta1.moderation_api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.moderation.v1beta1.AudioModerationRequest)
  })
_sym_db.RegisterMessage(AudioModerationRequest)

AudioModerationResponse = _reflection.GeneratedProtocolMessageType('AudioModerationResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOMODERATIONRESPONSE,
  '__module__' : 'speechly.moderation.v1beta1.moderation_api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.moderation.v1beta1.AudioModerationResponse)
  })
_sym_db.RegisterMessage(AudioModerationResponse)

StreamingAudioModerationRequest = _reflection.GeneratedProtocolMessageType('StreamingAudioModerationRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGAUDIOMODERATIONREQUEST,
  '__module__' : 'speechly.moderation.v1beta1.moderation_api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.moderation.v1beta1.StreamingAudioModerationRequest)
  })
_sym_db.RegisterMessage(StreamingAudioModerationRequest)

StreamingAudioModerationResponse = _reflection.GeneratedProtocolMessageType('StreamingAudioModerationResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGAUDIOMODERATIONRESPONSE,
  '__module__' : 'speechly.moderation.v1beta1.moderation_api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.moderation.v1beta1.StreamingAudioModerationResponse)
  })
_sym_db.RegisterMessage(StreamingAudioModerationResponse)


DESCRIPTOR._options = None

_MODERATIONAPI = _descriptor.ServiceDescriptor(
  name='ModerationAPI',
  full_name='speechly.moderation.v1beta1.ModerationAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=870,
  serialized_end=1294,
  methods=[
  _descriptor.MethodDescriptor(
    name='AudioModeration',
    full_name='speechly.moderation.v1beta1.ModerationAPI.AudioModeration',
    index=0,
    containing_service=None,
    input_type=_AUDIOMODERATIONREQUEST,
    output_type=_AUDIOMODERATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamingAudioModeration',
    full_name='speechly.moderation.v1beta1.ModerationAPI.StreamingAudioModeration',
    index=1,
    containing_service=None,
    input_type=_STREAMINGAUDIOMODERATIONREQUEST,
    output_type=_STREAMINGAUDIOMODERATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TextModeration',
    full_name='speechly.moderation.v1beta1.ModerationAPI.TextModeration',
    index=2,
    containing_service=None,
    input_type=_TEXTMODERATIONREQUEST,
    output_type=_TEXTMODERATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODERATIONAPI)

DESCRIPTOR.services_by_name['ModerationAPI'] = _MODERATIONAPI

# @@protoc_insertion_point(module_scope)
