# coding: utf-8

"""
    PrintNanny Factory API Documentation

    Documentation of API endpoints of printnanny-factory  # noqa: E501

    The version of the OpenAPI document: 0.1.0 
    Contact: leigh@printnanny.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DuetPrinterBackendStatusEnum(str, Enum):
    """
    * `disconnected` - Not connected to Duet * `starting` - Processing Duet config.g * `updating` - Duet firmware is being updated * `off` - The machine is turned off (i.e. the input voltage is too low for operation) * `halted` - The machine has encountered an emergency stop and is ready to reset * `pausing` - The machine is about to pause a file job * `paused` - The machine has paused a file job * `resuming` - The machine is about to resume a paused file job * `cancelling` - Job file is being cancelled * `processing` - The machine is processing a file job * `simulating` - The machine is simulating a file job to determine its processing time * `busy` - The machine is simulating a file job to determine its processing time * `changingTool` - The machine is changing the current tool * `idle` - The machine is on but has nothing to do
    """

    """
    allowed enum values
    """
    DISCONNECTED = 'disconnected'
    STARTING = 'starting'
    UPDATING = 'updating'
    OFF = 'off'
    HALTED = 'halted'
    PAUSING = 'pausing'
    PAUSED = 'paused'
    RESUMING = 'resuming'
    CANCELLING = 'cancelling'
    PROCESSING = 'processing'
    SIMULATING = 'simulating'
    BUSY = 'busy'
    CHANGINGTOOL = 'changingTool'
    IDLE = 'idle'

    @classmethod
    def from_json(cls, json_str: str) -> DuetPrinterBackendStatusEnum:
        """Create an instance of DuetPrinterBackendStatusEnum from a JSON string"""
        return DuetPrinterBackendStatusEnum(json.loads(json_str))


