
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-21T15:32:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "95bf4af1da801f2239adc100e2d0874ccb761cdf",
 "version": "2.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
