import threading
from typing import List
from win32com.client import DispatchEx as DispatchEx

class DmObject:
    def __init__(self) -> None: ...
    @classmethod
    def set_dll_path(cls, dm_reg_dll, dm_dll) -> None: ...
    def ex_reg(self): ...
    def get_project_path(self) -> str: ...
    def create(self): ...
    def enable_pic_cache(self, enable) -> int: ...
    def get_base_path(self) -> str: ...
    def get_dm_count(self) -> int: ...
    def get_id(self): ...
    def get_last_error(self) -> int: ...
    def get_path(self) -> str: ...
    def reg(self, code, ver_info) -> int: ...
    def reg_ex(self, code, ver_info, ip) -> int: ...
    def reg_ex_no_mac(self, code, ver_info, ip) -> int: ...
    def reg_no_mac(self, code, ver_info) -> int: ...
    def set_display_input(self, mode) -> int: ...
    def set_enum_window_delay(self, delay) -> int: ...
    def set_path(self, path) -> int: ...
    def set_show_error_msg(self, show) -> int: ...
    def speed_normal_graphic(self, enable) -> int: ...
    def ver(self) -> str: ...
    def client_to_screen(self, hwnd, x, y) -> str: ...
    def enum_process(self, name) -> str: ...
    def enum_window(self, parent, title, class_name, filter) -> str: ...
    def enum_window_by_process(self, process_name, title, class_name, filter) -> str: ...
    def enum_window_by_process_id(self, process_id, title, class_name, filter) -> str: ...
    def enum_window_super(self, spec1, flag1, type1, spec2, flag2, type2, sort) -> str: ...
    def find_window(self, class_name, title) -> int: ...
    def find_window_by_process(self, process_name, class_name, title) -> int: ...
    def find_window_by_process_id(self, process_id, class_name, title) -> int: ...
    def find_window_ex(self, parent, class_name, title) -> int: ...
    def find_window_super(self, spec1, flag1, type1, spec2, flag2, type2) -> int: ...
    def get_client_rect(self, hwnd) -> str: ...
    def get_client_size(self, hwnd) -> str: ...
    def get_foreground_focus(self) -> int: ...
    def get_foreground_window(self) -> int: ...
    def get_mouse_point_window(self) -> int: ...
    def get_point_window(self, x, y) -> int: ...
    def get_process_info(self, pid) -> str: ...
    def get_special_window(self, flag) -> int: ...
    def get_window(self, hwnd, flag) -> int: ...
    def get_window_class(self, hwnd) -> str: ...
    def get_window_process_id(self, hwnd) -> int: ...
    def get_window_process_path(self, hwnd) -> str: ...
    def get_window_rect(self, hwnd) -> str: ...
    def get_window_state(self, hwnd, flag) -> int: ...
    def get_window_thread_id(self, hwnd) -> int: ...
    def get_window_title(self, hwnd) -> str: ...
    def move_window(self, hwnd, x, y) -> int: ...
    def screen_to_client(self, hwnd, x, y) -> str: ...
    def send_paste(self, hwnd) -> int: ...
    def send_string(self, hwnd, msg) -> int: ...
    def send_string2(self, hwnd, msg) -> int: ...
    def send_string_ime(self, hwnd, msg) -> int: ...
    def set_client_size(self, hwnd, width, height) -> int: ...
    def set_window_size(self, hwnd, width, height) -> int: ...
    def set_window_state(self, hwnd, flag) -> int: ...
    def set_window_text(self, hwnd, title) -> int: ...
    def set_window_transparent(self, hwnd, v) -> int: ...
    def dm_guard(self, enable, g_type) -> int: ...
    def dm_guard_extract(self, dm_type, path) -> int: ...
    def dm_guard_load_custom(self, dm_type, path) -> int: ...
    def dm_guard_params(self, dm_type, param) -> int: ...
    def un_load_driver(self) -> int: ...
    def bind_window(self, hwnd, display, mouse, keypad, mode) -> int: ...
    def bind_window_ex(self, hwnd, display, mouse, keypad, public, mode) -> int: ...
    def down_cpu(self, rate) -> int: ...
    def enable_bind(self, en) -> int: ...
    def enable_fake_active(self, en) -> int: ...
    def enable_ime(self, en) -> int: ...
    def enable_keypad_msg(self, en) -> int: ...
    def enable_keypad_patch(self, en) -> int: ...
    def enable_keypad_sync(self, en) -> int: ...
    def enable_mouse_msg(self, en) -> int: ...
    def enable_mouse_sync(self, en) -> int: ...
    def enable_real_keypad(self, en) -> int: ...
    def enable_real_mouse(self, en, mouse_delay, mouse_step) -> int: ...
    def enable_speed_dx(self, en) -> int: ...
    def fource_un_bind_window(self, hwnd) -> int: ...
    def get_bind_window(self) -> int: ...
    def get_fps(self) -> int: ...
    def hack_speed(self, speed) -> int: ...
    def is_bind(self, hwnd) -> int: ...
    def lock_display(self, lock) -> int: ...
    def lock_input(self, lock) -> int: ...
    def lock_mouse_rect(self, x1, y1, x2, y2) -> int: ...
    def set_aero(self, en) -> int: ...
    def set_display_delay(self, t) -> int: ...
    def set_display_refresh_delay(self, t) -> int: ...
    def set_input_dm(self, dm) -> int: ...
    def switch_bind_window(self, hwnd) -> int: ...
    def un_bind_window(self) -> int: ...
    def enable_mouse_accuracy(self, en) -> int: ...
    def get_cursor_pos(self) -> tuple: ...
    def get_cursor_shape(self) -> tuple: ...
    def get_cursor_shape_ex(self, type) -> tuple: ...
    def get_cursor_spot(self) -> tuple: ...
    def get_key_state(self, vk) -> int: ...
    def get_mouse_speed(self) -> int: ...
    def key_down(self, vk) -> int: ...
    def key_down_char(self, key_str) -> int: ...
    def key_press(self, vk) -> int: ...
    def key_press_char(self, key_str) -> int: ...
    def key_press_str(self, key_str, delay) -> int: ...
    def key_up(self, vk) -> int: ...
    def key_up_char(self, key_str) -> int: ...
    def left_click(self) -> int: ...
    def left_double_click(self) -> int: ...
    def left_down(self) -> int: ...
    def left_up(self) -> int: ...
    def middle_click(self) -> int: ...
    def middle_double_click(self) -> int: ...
    def middle_down(self) -> int: ...
    def middle_up(self) -> int: ...
    def move_r(self, rx, ry) -> int: ...
    def move_to(self, x, y) -> int: ...
    def right_click(self) -> int: ...
    def right_down(self) -> int: ...
    def right_up(self) -> int: ...
    def set_keypad_delay(self, type, delay) -> int: ...
    def set_mouse_delay(self, type, delay) -> int: ...
    def set_mouse_speed(self, speed) -> int: ...
    def set_sim_mode(self, mode) -> int: ...
    def wait_key(self, vk, time_out) -> int: ...
    def wheel_down(self) -> int: ...
    def wheel_up(self) -> int: ...
    def append_pic_addr(self, addr) -> int: ...
    def bgr_2_rgb(self, bgr_color) -> int: ...
    def capture(self, x1, y1, x2, y2, file) -> int: ...
    def capture_gif(self, x1, y1, x2, y2, file, delay, time) -> int: ...
    def capture_jpg(self, x1, y1, x2, y2, file, quality) -> int: ...
    def capture_png(self, x1, y1, x2, y2, file) -> int: ...
    def capture_pre(self, file) -> int: ...
    def cmp_color(self, x, y, color, sim) -> int: ...
    def enable_display_debug(self, enable_debug) -> int: ...
    def enable_find_pic_multithread(self, enable) -> int: ...
    def enable_get_color_by_capture(self, enable) -> int: ...
    def find_color(self, x1, y1, x2, y2, color, sim, dir) -> str: ...
    def find_color_block(self, x1, y1, x2, y2, color, sim, count, width, height, dir) -> str: ...
    def find_color_block_ex(self, x1, y1, x2, y2, color, sim, count, width, height, dir) -> str: ...
    def find_color_ex(self, x1, y1, x2, y2, color, sim, dir) -> str: ...
    def find_mul_color(self, x1, y1, x2, y2, color, sim) -> str: ...
    def find_multi_color(self, x1, y1, x2, y2, first_color, offset_color, sim, dir) -> str: ...
    def find_multi_color_ex(self, x1, y1, x2, y2, first_color, offset_color, sim, dir) -> str: ...
    def find_pic(self, x1, y1, x2, y2, pic_name, delta_color, sim, dir) -> str: ...
    def find_pic_ex(self, x1, y1, x2, y2, pic_name, delta_color, sim, dir) -> str: ...
    def find_pic_ex_s(self, x1, y1, x2, y2, pic_name, delta_color, sim, dir) -> str: ...
    def find_pic_mem(self, x1, y1, x2, y2, pic_info, delta_color, sim, dir) -> str: ...
    def find_pic_mem_ex(self, x1, y1, x2, y2, pic_info, delta_color, sim, dir) -> str: ...
    def find_pic_s(self, x1, y1, x2, y2, pic_name, delta_color, sim, dir) -> str: ...
    def find_shape(self, x1, y1, x2, y2, offset_color, sim, dir) -> str: ...
    def find_shape_ex(self, x1, y1, x2, y2, offset_color, sim, dir) -> str: ...
    def free_pic(self, pic_name) -> int: ...
    def get_ave_hsv(self, x1, y1, x2, y2) -> str: ...
    def get_ave_rgb(self, x1, y1, x2, y2) -> str: ...
    def get_color(self, x, y) -> str: ...
    def get_color_bgr(self, x, y) -> str: ...
    def get_color_hsv(self, x, y) -> str: ...
    def get_color_num(self, x1, y1, x2, y2, color, sim) -> int: ...
    def get_pic_size(self, pic_name) -> str: ...
    def get_screen_data(self, x1, y1, x2, y2) -> str: ...
    def get_screen_data_bmp(self, x1, y1, x2, y2) -> str: ...
    def image_to_bmp(self, pic_name, bmp_name) -> int: ...
    def is_display_dead(self, x1, y1, x2, y2, t) -> int: ...
    def load_pic(self, pic_name) -> int: ...
    def load_pic_byte(self, pic_name, data, size) -> int: ...
    def match_pic_name(self, pic_name) -> str: ...
    def rgb_2_bgr(self, rgb_color) -> str: ...
    def set_exclde_region(self, t, x1, y1, x2, y2) -> int: ...
    def set_find_pic_multithread_count(self, count) -> int: ...
    def set_find_pic_multithread_limit(self, limit) -> int: ...
    def set_pic_pwd(self, pwd) -> int: ...
    def add_dict(self, index, dict_info) -> int: ...
    def clear_dict(self, index) -> int: ...
    def enable_share_dict(self, enbale) -> int: ...
    def fetch_word(self, x1, y1, x2, y2, color, word) -> str: ...
    def find_str(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_e(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_ex(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_ex_s(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_fast(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_fast_s(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_fast_ex(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_fast_e(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_fast_ex_s(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_s(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_with_font(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_with_font_e(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def find_str_with_font_ex(self, x1, y1, x2, y2, string, color_format, sim: float = ...) -> str: ...
    def get_dict(self, index) -> str: ...
    def get_dict_count(self, index) -> int: ...
    def get_dict_info(self, index, font_name, font_size, flag) -> str: ...
    def get_now_dict(self) -> int: ...
    def get_result_count(self) -> int: ...
    def get_result_pos(self, index) -> str: ...
    def get_result_str(self, index) -> str: ...
    def get_words(self, x1, y1, x2, y2, color_format, sim: float = ...) -> str: ...
    def get_words_no_dict(self, x1, y1, x2, y2, color_format, sim: float = ...) -> str: ...
    def ocr(self, x1, y1, x2, y2, color_format, sim: float = ...) -> str: ...
    def ocr_ex(self, x1, y1, x2, y2, color_format, sim: float = ...) -> str: ...
    def ocr_ex_one(self, x1, y1, x2, y2, color_format, sim: float = ...) -> str: ...
    def ocr_in_file(self, x1, y1, x2, y2, pic_name, color_format, sim: float = ...) -> str: ...
    def save_dict(self, index, file) -> int: ...
    def set_col_gap_no_dict(self, col_gap) -> int: ...
    def set_dict(self, index, file) -> int: ...
    def set_dict_mem(self, index, addr, size) -> int: ...
    def set_dict_pwd(self, pwd) -> int: ...
    def set_exact_ocr(self, exact_ocr) -> int: ...
    def set_min_col_gap(self, col_gap) -> int: ...
    def set_min_row_gap(self, row_gap) -> int: ...
    def set_row_gap_no_dict(self, row_gap) -> int: ...
    def set_word_gap(self, word_gap) -> int: ...
    def set_word_gap_no_dict(self, word_gap) -> int: ...
    def set_word_line_height(self, line_height) -> int: ...
    def set_word_line_height_no_dict(self, line_height) -> int: ...
    def use_dict(self, index) -> int: ...
    def __getattr__(self, name, *args, **kwargs): ...

class DataStruct:
    dm: DmObject
    thread: str
    hwnd: str
    def __init__(self) -> None: ...
    def clear(self) -> None: ...

gl_data: DataStruct
td_data: List[DataStruct]

class Thread(threading.Thread):
    handle: str
    daemon: bool
    def __init__(self, target: callable, *args, **kwargs) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self): ...
    def resume(self): ...
