# -*- coding: utf-8 -*-
# Generated by Django 4.1.6 on 2023-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="eta",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="expires",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_eager",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="retries",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="root_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
