# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_3D_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Simple3DViewer(object):
    def setupUi(self, Simple3DViewer):
        Simple3DViewer.setObjectName("Simple3DViewer")
        Simple3DViewer.resize(1312, 937)
        self.centralwidget = QtWidgets.QWidget(Simple3DViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.volumeLabel = QtWidgets.QLabel(self.frame)
        self.volumeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.volumeLabel.setObjectName("volumeLabel")
        self.gridLayout_2.addWidget(self.volumeLabel, 0, 1, 1, 2)
        self.colorbarGraphicsView = QtWidgets.QGraphicsView(self.frame)
        self.colorbarGraphicsView.setMaximumSize(QtCore.QSize(16777215, 20))
        self.colorbarGraphicsView.setObjectName("colorbarGraphicsView")
        self.gridLayout_2.addWidget(self.colorbarGraphicsView, 2, 1, 1, 1)
        self.minContrast = QtWidgets.QLabel(self.frame)
        self.minContrast.setObjectName("minContrast")
        self.gridLayout_2.addWidget(self.minContrast, 2, 0, 1, 1)
        self.leftGraphicsView = QtWidgets.QGraphicsView(self.frame)
        self.leftGraphicsView.setObjectName("leftGraphicsView")
        self.gridLayout_2.addWidget(self.leftGraphicsView, 1, 0, 1, 3)
        self.maxContrast = QtWidgets.QLabel(self.frame)
        self.maxContrast.setObjectName("maxContrast")
        self.gridLayout_2.addWidget(self.maxContrast, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.previousImageButton = QtWidgets.QPushButton(self.groupBox)
        self.previousImageButton.setObjectName("previousImageButton")
        self.gridLayout_3.addWidget(self.previousImageButton, 3, 0, 1, 1)
        self.imageDirLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.imageDirLineEdit.setObjectName("imageDirLineEdit")
        self.gridLayout_3.addWidget(self.imageDirLineEdit, 1, 0, 1, 3)
        self.nextImageButton = QtWidgets.QPushButton(self.groupBox)
        self.nextImageButton.setObjectName("nextImageButton")
        self.gridLayout_3.addWidget(self.nextImageButton, 3, 3, 1, 1)
        self.imageComboBox = QtWidgets.QComboBox(self.groupBox)
        self.imageComboBox.setObjectName("imageComboBox")
        self.gridLayout_3.addWidget(self.imageComboBox, 3, 1, 1, 2)
        self.imageDirSelectButton = QtWidgets.QPushButton(self.groupBox)
        self.imageDirSelectButton.setObjectName("imageDirSelectButton")
        self.gridLayout_3.addWidget(self.imageDirSelectButton, 1, 3, 1, 1)
        self.selectImageLabel = QtWidgets.QLabel(self.groupBox)
        self.selectImageLabel.setObjectName("selectImageLabel")
        self.gridLayout_3.addWidget(self.selectImageLabel, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout.setObjectName("gridLayout")
        self.minContrastSlider = QtWidgets.QSlider(self.groupBox_8)
        self.minContrastSlider.setMinimumSize(QtCore.QSize(150, 0))
        self.minContrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minContrastSlider.setObjectName("minContrastSlider")
        self.gridLayout.addWidget(self.minContrastSlider, 1, 1, 1, 2)
        self.maxContrastSlider = QtWidgets.QSlider(self.groupBox_8)
        self.maxContrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxContrastSlider.setObjectName("maxContrastSlider")
        self.gridLayout.addWidget(self.maxContrastSlider, 2, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addWidget(self.frame_9, 3, 1, 1, 4)
        self.minContrast1 = QtWidgets.QLabel(self.groupBox_8)
        self.minContrast1.setObjectName("minContrast1")
        self.gridLayout.addWidget(self.minContrast1, 1, 0, 1, 1)
        self.contrastLabel = QtWidgets.QLabel(self.groupBox_8)
        self.contrastLabel.setObjectName("contrastLabel")
        self.gridLayout.addWidget(self.contrastLabel, 0, 0, 1, 2)
        self.maxContrast1 = QtWidgets.QLabel(self.groupBox_8)
        self.maxContrast1.setObjectName("maxContrast1")
        self.gridLayout.addWidget(self.maxContrast1, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 5, 0, 1, 4)
        self.frame_8 = QtWidgets.QFrame(self.groupBox)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectSliceLabel = QtWidgets.QLabel(self.frame_8)
        self.selectSliceLabel.setObjectName("selectSliceLabel")
        self.verticalLayout.addWidget(self.selectSliceLabel)
        self.sliceSlider = QtWidgets.QSlider(self.frame_8)
        self.sliceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sliceSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sliceSlider.setTickInterval(1)
        self.sliceSlider.setObjectName("sliceSlider")
        self.verticalLayout.addWidget(self.sliceSlider)
        self.gridLayout_3.addWidget(self.frame_8, 4, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 7, 1, 1, 1)
        self.imageListTextEdit = QtWidgets.QTextEdit(self.groupBox)
        self.imageListTextEdit.setObjectName("imageListTextEdit")
        self.gridLayout_3.addWidget(self.imageListTextEdit, 6, 0, 2, 4)
        self.horizontalLayout.addWidget(self.groupBox)
        Simple3DViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Simple3DViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 21))
        self.menubar.setObjectName("menubar")
        Simple3DViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Simple3DViewer)
        self.statusbar.setObjectName("statusbar")
        Simple3DViewer.setStatusBar(self.statusbar)

        self.retranslateUi(Simple3DViewer)
        QtCore.QMetaObject.connectSlotsByName(Simple3DViewer)

    def retranslateUi(self, Simple3DViewer):
        _translate = QtCore.QCoreApplication.translate
        Simple3DViewer.setWindowTitle(_translate("Simple3DViewer", "Simple 3D viewer"))
        self.volumeLabel.setText(_translate("Simple3DViewer", "Volume 1"))
        self.minContrast.setText(_translate("Simple3DViewer", "Min"))
        self.maxContrast.setText(_translate("Simple3DViewer", "Max"))
        self.groupBox.setTitle(_translate("Simple3DViewer", "Controls"))
        self.previousImageButton.setText(_translate("Simple3DViewer", "Previous"))
        self.nextImageButton.setText(_translate("Simple3DViewer", "Next"))
        self.imageDirSelectButton.setText(_translate("Simple3DViewer", "Select"))
        self.selectImageLabel.setText(_translate("Simple3DViewer", "Select image:"))
        self.label.setText(_translate("Simple3DViewer", "Image folder:"))
        self.minContrast1.setText(_translate("Simple3DViewer", "Min"))
        self.contrastLabel.setText(_translate("Simple3DViewer", "Min/max contrast"))
        self.maxContrast1.setText(_translate("Simple3DViewer", "Max"))
        self.selectSliceLabel.setText(_translate("Simple3DViewer", "Select slice:"))

