
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-15T16:12:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b95a6944543d0893c2677a50a9c137cf8ba41dc8",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
