STATUS_QUERY = [
    "index",
    "timestamp",
    "driver_version",
    "count",
    "name",
    "serial",
    "uuid",
    "display_mode",
    "persistence_mode",
    "fan.speed",
    "pstate",
    "memory.total",
    "memory.used",
    "memory.free",
    "utilization.gpu",
    "temperature.gpu",
    "power.draw",
    "power.draw.average",
    "power.limit",
    "power.max_limit",
]

COMPUTE_QUERY = [
    "timestamp",
    "gpu_name",
    "gpu_bus_id",
    "gpu_serial",
    "gpu_uuid",
    "pid",
    "process_name",
    "used_gpu_memory",
]