
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-21T13:11:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "41121674291a01fd622f798186c03f49a3af8f3a",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
