ANNOT_PATH = "annotations"
DATA_PATH = "data"
GROUND_TRUTH_FOLDER = "annotations/groundtruth/"
BBOX_NAME = "bbox_shape"
IMAGE_EXT = ".jpg"
COCO_LABEL_FILE = "labels.json"

LOGGING_FORMAT = "%(asctime)s[%(process)d][%(levelname)s] %(name)-16s : %(message)s"
LOGGING_DATEFMT = "[%d-%m-%Y %H:%M:%S]"
VISIONAI_OBJECT_JSON = "objects.json"
