# Generated by Django 4.2.4 on 2023-08-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ihs_id', models.CharField(auto_created=True, max_length=255)),
                ('ihs_url', models.CharField(max_length=255)),
                ('ihs_response', models.CharField(max_length=255)),
                ('ihs_cr_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nms_node_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetupProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spd_node_id', models.CharField(max_length=50)),
                ('spd_node_category', models.CharField(max_length=50)),
                ('spd_ref_id', models.CharField(max_length=100)),
                ('spd_download_location', models.CharField(blank=True, max_length=255)),
                ('spd_download_start_time', models.DateTimeField(auto_now_add=True)),
                ('spd_download_end_time', models.DateTimeField(blank=True, null=True)),
                ('spd_download_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_node_id', models.CharField(max_length=50)),
                ('td_api_status', models.CharField(max_length=100)),
                ('td_cr_timestamp', models.DateTimeField(auto_now_add=True)),
                ('td_count', models.IntegerField()),
            ],
        ),
    ]
