# Generated by Django 4.2.1 on 2023-08-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nms_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPHealthStatus',
        ),
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
    ]
