
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-24T12:09:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4fae982fb49a12f760f31a39cfcfd6a735f153a",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
