# Generated by Django 2.2.23 on 2022-06-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahoe_idp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclink',
            name='redirect_url',
            field=models.TextField(null=True),
        ),
    ]
