VERSION_YEAR = 2023
VERSION_MONTH = int('08')
VERSION_DAY = int('19')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('55')
MAJOR_VERSION = 1
MINOR_VERSION = 15
PATCH_VERSION = 202308191055
version_date = '2023/08/19 10:55'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
