
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-24T13:54:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9aa11a2f34b746822a639989af8c3f46b1461279",
 "version": "0.1.6.post0.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
