# coding: utf-8

"""
    PrintNanny Factory API Documentation

    Documentation of API endpoints of printnanny-factory  # noqa: E501

    The version of the OpenAPI document: 0.1.0 
    Contact: leigh@printnanny.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import printnanny_factory_rest_api
from printnanny_factory_rest_api.models.patched_print_job_request_all_of import PatchedPrintJobRequestAllOf  # noqa: E501
from printnanny_factory_rest_api.rest import ApiException

class TestPatchedPrintJobRequestAllOf(unittest.TestCase):
    """PatchedPrintJobRequestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PatchedPrintJobRequestAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedPrintJobRequestAllOf`
        """
        model = printnanny_factory_rest_api.models.patched_print_job_request_all_of.PatchedPrintJobRequestAllOf()  # noqa: E501
        if include_optional :
            return PatchedPrintJobRequestAllOf(
                progress = -2147483648, 
                estimated_print_seconds = -9223372036854775808, 
                clear_dt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                status = 'queued', 
                batch = ''
            )
        else :
            return PatchedPrintJobRequestAllOf(
        )
        """

    def testPatchedPrintJobRequestAllOf(self):
        """Test PatchedPrintJobRequestAllOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
