VERSION_YEAR = 2023
VERSION_MONTH = int('08')
VERSION_DAY = int('22')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('26')
MAJOR_VERSION = 0
MINOR_VERSION = 8
PATCH_VERSION = 202308221026
version_date = '2023/08/22 10:26'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
