# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class ResponseArtifact(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file': 'StorageFile',
        'is_dir': 'bool',
        'nfs_path': 'str',
        'relative_path_to_volume': 'str'
    }

    attribute_map = {
        'file': 'file',
        'is_dir': 'is_dir',
        'nfs_path': 'nfs_path',
        'relative_path_to_volume': 'relative_path_to_volume'
    }

    def __init__(self, file=None, is_dir=None, nfs_path=None, relative_path_to_volume=None, local_vars_configuration=None):  # noqa: E501
        """ResponseArtifact - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._file = None
        self._is_dir = None
        self._nfs_path = None
        self._relative_path_to_volume = None
        self.discriminator = None

        if file is not None:
            self.file = file
        if is_dir is not None:
            self.is_dir = is_dir
        if nfs_path is not None:
            self.nfs_path = nfs_path
        if relative_path_to_volume is not None:
            self.relative_path_to_volume = relative_path_to_volume

    @property
    def file(self):
        """Gets the file of this ResponseArtifact.  # noqa: E501


        :return: The file of this ResponseArtifact.  # noqa: E501
        :rtype: StorageFile
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this ResponseArtifact.


        :param file: The file of this ResponseArtifact.  # noqa: E501
        :type file: StorageFile
        """

        self._file = file

    @property
    def is_dir(self):
        """Gets the is_dir of this ResponseArtifact.  # noqa: E501


        :return: The is_dir of this ResponseArtifact.  # noqa: E501
        :rtype: bool
        """
        return self._is_dir

    @is_dir.setter
    def is_dir(self, is_dir):
        """Sets the is_dir of this ResponseArtifact.


        :param is_dir: The is_dir of this ResponseArtifact.  # noqa: E501
        :type is_dir: bool
        """

        self._is_dir = is_dir

    @property
    def nfs_path(self):
        """Gets the nfs_path of this ResponseArtifact.  # noqa: E501


        :return: The nfs_path of this ResponseArtifact.  # noqa: E501
        :rtype: str
        """
        return self._nfs_path

    @nfs_path.setter
    def nfs_path(self, nfs_path):
        """Sets the nfs_path of this ResponseArtifact.


        :param nfs_path: The nfs_path of this ResponseArtifact.  # noqa: E501
        :type nfs_path: str
        """

        self._nfs_path = nfs_path

    @property
    def relative_path_to_volume(self):
        """Gets the relative_path_to_volume of this ResponseArtifact.  # noqa: E501


        :return: The relative_path_to_volume of this ResponseArtifact.  # noqa: E501
        :rtype: str
        """
        return self._relative_path_to_volume

    @relative_path_to_volume.setter
    def relative_path_to_volume(self, relative_path_to_volume):
        """Sets the relative_path_to_volume of this ResponseArtifact.


        :param relative_path_to_volume: The relative_path_to_volume of this ResponseArtifact.  # noqa: E501
        :type relative_path_to_volume: str
        """

        self._relative_path_to_volume = relative_path_to_volume

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseArtifact):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResponseArtifact):
            return True

        return self.to_dict() != other.to_dict()
