
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-22T15:05:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fe42fc73c7a534693e91b37fc71f5c44c2aca1f",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
