# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/private/event/v1/connection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='speechly/private/event/v1/connection.proto',
  package='speechly.private.event.v1',
  syntax='proto3',
  serialized_options=b'\n\036com.speechly.internal.event.v1P\001Z!speechly/private/event/v1;eventv1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*speechly/private/event/v1/connection.proto\x12\x19speechly.private.event.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x05\n\x0f\x43onnectionEvent\x12\x15\n\rconnection_id\x18\x01 \x01(\t\x12\x45\n\x08protocol\x18\x02 \x01(\x0e\x32\x33.speechly.private.event.v1.ConnectionEvent.Protocol\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x11\n\tdevice_id\x18\x05 \x01(\t\x12\x12\n\nuser_agent\x18\x06 \x01(\t\x12\x11\n\tsource_ip\x18\x07 \x01(\t\x12\x19\n\x11remote_latency_ms\x18\x08 \x01(\x02\x12\x18\n\x10\x63\x61ll_overhead_ms\x18\t \x01(\x02\x12\x13\n\x0b\x64uration_ms\x18\n \x01(\x02\x12\x41\n\x06status\x18\x0b \x01(\x0e\x32\x31.speechly.private.event.v1.ConnectionEvent.Status\x12.\n\nstart_time\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tstop_time\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\napi_region\x18\x0e \x01(\t\x12\x0f\n\x07referer\x18\x0f \x01(\t\"b\n\x08Protocol\x12\x14\n\x10PROTOCOL_UNKNOWN\x10\x00\x12\x16\n\x12PROTOCOL_WEBSOCKET\x10\x01\x12\x11\n\rPROTOCOL_GRPC\x10\x02\x12\x15\n\x11PROTOCOL_ONDEVICE\x10\x03\"\x7f\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x1a\n\x16STATUS_UNAUTHENTICATED\x10\x02\x12\x1b\n\x17STATUS_ILLEGAL_ARGUMENT\x10\x03\x12\x19\n\x15STATUS_INTERNAL_ERROR\x10\x04\x42\x45\n\x1e\x63om.speechly.internal.event.v1P\x01Z!speechly/private/event/v1;eventv1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_CONNECTIONEVENT_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='speechly.private.event.v1.ConnectionEvent.Protocol',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_WEBSOCKET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_GRPC', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_ONDEVICE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=579,
  serialized_end=677,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONEVENT_PROTOCOL)

_CONNECTIONEVENT_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='speechly.private.event.v1.ConnectionEvent.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_OK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNAUTHENTICATED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ILLEGAL_ARGUMENT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INTERNAL_ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=679,
  serialized_end=806,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONEVENT_STATUS)


_CONNECTIONEVENT = _descriptor.Descriptor(
  name='ConnectionEvent',
  full_name='speechly.private.event.v1.ConnectionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connection_id', full_name='speechly.private.event.v1.ConnectionEvent.connection_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='speechly.private.event.v1.ConnectionEvent.protocol', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='host', full_name='speechly.private.event.v1.ConnectionEvent.host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='speechly.private.event.v1.ConnectionEvent.path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='speechly.private.event.v1.ConnectionEvent.device_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_agent', full_name='speechly.private.event.v1.ConnectionEvent.user_agent', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_ip', full_name='speechly.private.event.v1.ConnectionEvent.source_ip', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remote_latency_ms', full_name='speechly.private.event.v1.ConnectionEvent.remote_latency_ms', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='call_overhead_ms', full_name='speechly.private.event.v1.ConnectionEvent.call_overhead_ms', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_ms', full_name='speechly.private.event.v1.ConnectionEvent.duration_ms', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='speechly.private.event.v1.ConnectionEvent.status', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='speechly.private.event.v1.ConnectionEvent.start_time', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop_time', full_name='speechly.private.event.v1.ConnectionEvent.stop_time', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_region', full_name='speechly.private.event.v1.ConnectionEvent.api_region', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='referer', full_name='speechly.private.event.v1.ConnectionEvent.referer', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONNECTIONEVENT_PROTOCOL,
    _CONNECTIONEVENT_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=806,
)

_CONNECTIONEVENT.fields_by_name['protocol'].enum_type = _CONNECTIONEVENT_PROTOCOL
_CONNECTIONEVENT.fields_by_name['status'].enum_type = _CONNECTIONEVENT_STATUS
_CONNECTIONEVENT.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CONNECTIONEVENT.fields_by_name['stop_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CONNECTIONEVENT_PROTOCOL.containing_type = _CONNECTIONEVENT
_CONNECTIONEVENT_STATUS.containing_type = _CONNECTIONEVENT
DESCRIPTOR.message_types_by_name['ConnectionEvent'] = _CONNECTIONEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectionEvent = _reflection.GeneratedProtocolMessageType('ConnectionEvent', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONEVENT,
  '__module__' : 'speechly.private.event.v1.connection_pb2'
  # @@protoc_insertion_point(class_scope:speechly.private.event.v1.ConnectionEvent)
  })
_sym_db.RegisterMessage(ConnectionEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
