# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechly/private/asr/v2/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speechly/private/asr/v2/api.proto',
  package='speechly.private.asr.v2',
  syntax='proto3',
  serialized_options=b'\n\034com.speechly.internal.asr.v2P\001Z\035speechly/private/asr/v2;asrv2',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!speechly/private/asr/v2/api.proto\x12\x17speechly.private.asr.v2\"\xb2\x01\n\x11TranscribeRequest\x12\x41\n\x0c\x61udio_config\x18\x01 \x01(\x0b\x32+.speechly.private.asr.v2.AudioConfiguration\x12K\n\x11processing_config\x18\x02 \x01(\x0b\x32\x30.speechly.private.asr.v2.ProcessingConfiguration\x12\r\n\x05\x61udio\x18\x03 \x01(\x0c\"\xb1\x01\n\x12\x41udioConfiguration\x12\x19\n\x11sample_rate_hertz\x18\x01 \x01(\x05\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\x12\x43\n\x07options\x18\x03 \x03(\x0b\x32\x32.speechly.private.asr.v2.AudioConfiguration.Option\x1a$\n\x06Option\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x03(\t\"i\n\x17ProcessingConfiguration\x12\x10\n\x08tokenize\x18\x01 \x01(\x08\x12\x11\n\ttranslate\x18\x02 \x01(\x08\x12\x17\n\x0fskip_transcribe\x18\x03 \x01(\x08\x12\x10\n\x08model_id\x18\x04 \x01(\t\"N\n\x12TranscribeResponse\x12\x38\n\x0btranscripts\x18\x01 \x03(\x0b\x32#.speechly.private.asr.v2.Transcript\"\xa9\x02\n\nTranscript\x12\x10\n\x08language\x18\x01 \x01(\t\x12@\n\x04type\x18\x02 \x01(\x0e\x32\x32.speechly.private.asr.v2.Transcript.TranscriptType\x12\x0c\n\x04text\x18\x03 \x01(\t\x12.\n\x06tokens\x18\x04 \x03(\x0b\x32\x1e.speechly.private.asr.v2.Token\"\x88\x01\n\x0eTranscriptType\x12\x1b\n\x17TRANSCRIPT_TYPE_INVALID\x10\x00\x12\x1b\n\x17TRANSCRIPT_TYPE_LEXICAL\x10\x01\x12\x1b\n\x17TRANSCRIPT_TYPE_DISPLAY\x10\x02\x12\x1f\n\x1bTRANSCRIPT_TYPE_TRANSLATION\x10\x03\"K\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x12\n\nstart_time\x18\x03 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x05\x32n\n\x03\x41SR\x12g\n\nTranscribe\x12*.speechly.private.asr.v2.TranscribeRequest\x1a+.speechly.private.asr.v2.TranscribeResponse(\x01\x42?\n\x1c\x63om.speechly.internal.asr.v2P\x01Z\x1dspeechly/private/asr/v2;asrv2b\x06proto3'
)



_TRANSCRIPT_TRANSCRIPTTYPE = _descriptor.EnumDescriptor(
  name='TranscriptType',
  full_name='speechly.private.asr.v2.Transcript.TranscriptType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRANSCRIPT_TYPE_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSCRIPT_TYPE_LEXICAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSCRIPT_TYPE_DISPLAY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSCRIPT_TYPE_TRANSLATION', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=772,
  serialized_end=908,
)
_sym_db.RegisterEnumDescriptor(_TRANSCRIPT_TRANSCRIPTTYPE)


_TRANSCRIBEREQUEST = _descriptor.Descriptor(
  name='TranscribeRequest',
  full_name='speechly.private.asr.v2.TranscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_config', full_name='speechly.private.asr.v2.TranscribeRequest.audio_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processing_config', full_name='speechly.private.asr.v2.TranscribeRequest.processing_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio', full_name='speechly.private.asr.v2.TranscribeRequest.audio', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=241,
)


_AUDIOCONFIGURATION_OPTION = _descriptor.Descriptor(
  name='Option',
  full_name='speechly.private.asr.v2.AudioConfiguration.Option',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='speechly.private.asr.v2.AudioConfiguration.Option.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='speechly.private.asr.v2.AudioConfiguration.Option.value', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=421,
)

_AUDIOCONFIGURATION = _descriptor.Descriptor(
  name='AudioConfiguration',
  full_name='speechly.private.asr.v2.AudioConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_rate_hertz', full_name='speechly.private.asr.v2.AudioConfiguration.sample_rate_hertz', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language_code', full_name='speechly.private.asr.v2.AudioConfiguration.language_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='options', full_name='speechly.private.asr.v2.AudioConfiguration.options', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_AUDIOCONFIGURATION_OPTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=421,
)


_PROCESSINGCONFIGURATION = _descriptor.Descriptor(
  name='ProcessingConfiguration',
  full_name='speechly.private.asr.v2.ProcessingConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokenize', full_name='speechly.private.asr.v2.ProcessingConfiguration.tokenize', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translate', full_name='speechly.private.asr.v2.ProcessingConfiguration.translate', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skip_transcribe', full_name='speechly.private.asr.v2.ProcessingConfiguration.skip_transcribe', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='speechly.private.asr.v2.ProcessingConfiguration.model_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=528,
)


_TRANSCRIBERESPONSE = _descriptor.Descriptor(
  name='TranscribeResponse',
  full_name='speechly.private.asr.v2.TranscribeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transcripts', full_name='speechly.private.asr.v2.TranscribeResponse.transcripts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=608,
)


_TRANSCRIPT = _descriptor.Descriptor(
  name='Transcript',
  full_name='speechly.private.asr.v2.Transcript',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='speechly.private.asr.v2.Transcript.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='speechly.private.asr.v2.Transcript.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='speechly.private.asr.v2.Transcript.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='speechly.private.asr.v2.Transcript.tokens', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSCRIPT_TRANSCRIPTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=908,
)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='speechly.private.asr.v2.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='speechly.private.asr.v2.Token.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='speechly.private.asr.v2.Token.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='speechly.private.asr.v2.Token.start_time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='speechly.private.asr.v2.Token.end_time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=910,
  serialized_end=985,
)

_TRANSCRIBEREQUEST.fields_by_name['audio_config'].message_type = _AUDIOCONFIGURATION
_TRANSCRIBEREQUEST.fields_by_name['processing_config'].message_type = _PROCESSINGCONFIGURATION
_AUDIOCONFIGURATION_OPTION.containing_type = _AUDIOCONFIGURATION
_AUDIOCONFIGURATION.fields_by_name['options'].message_type = _AUDIOCONFIGURATION_OPTION
_TRANSCRIBERESPONSE.fields_by_name['transcripts'].message_type = _TRANSCRIPT
_TRANSCRIPT.fields_by_name['type'].enum_type = _TRANSCRIPT_TRANSCRIPTTYPE
_TRANSCRIPT.fields_by_name['tokens'].message_type = _TOKEN
_TRANSCRIPT_TRANSCRIPTTYPE.containing_type = _TRANSCRIPT
DESCRIPTOR.message_types_by_name['TranscribeRequest'] = _TRANSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['AudioConfiguration'] = _AUDIOCONFIGURATION
DESCRIPTOR.message_types_by_name['ProcessingConfiguration'] = _PROCESSINGCONFIGURATION
DESCRIPTOR.message_types_by_name['TranscribeResponse'] = _TRANSCRIBERESPONSE
DESCRIPTOR.message_types_by_name['Transcript'] = _TRANSCRIPT
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TranscribeRequest = _reflection.GeneratedProtocolMessageType('TranscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIBEREQUEST,
  '__module__' : 'speechly.private.asr.v2.api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.private.asr.v2.TranscribeRequest)
  })
_sym_db.RegisterMessage(TranscribeRequest)

AudioConfiguration = _reflection.GeneratedProtocolMessageType('AudioConfiguration', (_message.Message,), {

  'Option' : _reflection.GeneratedProtocolMessageType('Option', (_message.Message,), {
    'DESCRIPTOR' : _AUDIOCONFIGURATION_OPTION,
    '__module__' : 'speechly.private.asr.v2.api_pb2'
    # @@protoc_insertion_point(class_scope:speechly.private.asr.v2.AudioConfiguration.Option)
    })
  ,
  'DESCRIPTOR' : _AUDIOCONFIGURATION,
  '__module__' : 'speechly.private.asr.v2.api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.private.asr.v2.AudioConfiguration)
  })
_sym_db.RegisterMessage(AudioConfiguration)
_sym_db.RegisterMessage(AudioConfiguration.Option)

ProcessingConfiguration = _reflection.GeneratedProtocolMessageType('ProcessingConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSINGCONFIGURATION,
  '__module__' : 'speechly.private.asr.v2.api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.private.asr.v2.ProcessingConfiguration)
  })
_sym_db.RegisterMessage(ProcessingConfiguration)

TranscribeResponse = _reflection.GeneratedProtocolMessageType('TranscribeResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIBERESPONSE,
  '__module__' : 'speechly.private.asr.v2.api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.private.asr.v2.TranscribeResponse)
  })
_sym_db.RegisterMessage(TranscribeResponse)

Transcript = _reflection.GeneratedProtocolMessageType('Transcript', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIPT,
  '__module__' : 'speechly.private.asr.v2.api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.private.asr.v2.Transcript)
  })
_sym_db.RegisterMessage(Transcript)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'speechly.private.asr.v2.api_pb2'
  # @@protoc_insertion_point(class_scope:speechly.private.asr.v2.Token)
  })
_sym_db.RegisterMessage(Token)


DESCRIPTOR._options = None

_ASR = _descriptor.ServiceDescriptor(
  name='ASR',
  full_name='speechly.private.asr.v2.ASR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=987,
  serialized_end=1097,
  methods=[
  _descriptor.MethodDescriptor(
    name='Transcribe',
    full_name='speechly.private.asr.v2.ASR.Transcribe',
    index=0,
    containing_service=None,
    input_type=_TRANSCRIBEREQUEST,
    output_type=_TRANSCRIBERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASR)

DESCRIPTOR.services_by_name['ASR'] = _ASR

# @@protoc_insertion_point(module_scope)
