# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/langchain_guidelines',
                'doc_host': 'https://HamzaFarhan.github.io',
                'git_url': 'https://github.com/HamzaFarhan/langchain_guidelines',
                'lib_path': 'langchain_guidelines'},
  'syms': {'langchain_guidelines.core': {'langchain_guidelines.core.foo': ('core.html#foo', 'langchain_guidelines/core.py')}}}
