# coding: utf-8

"""
    Empire - Platform API

    OpenAPI specification for the Platform REST API of Empire  **System Time:** Europe/Amsterdam  **General data formats:**   * _capacity values_ => kW (integers)   * _dates and local times_ => System Time   * _currencies_ => EUR   # noqa: E501

    The version of the OpenAPI document: 0.179.13
    Contact: britned.info@britned.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import empire_platform_api_public_client
from empire_platform_api_public_client.models.mtu_period import MtuPeriod  # noqa: E501
from empire_platform_api_public_client.rest import ApiException

class TestMtuPeriod(unittest.TestCase):
    """MtuPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MtuPeriod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MtuPeriod`
        """
        model = empire_platform_api_public_client.models.mtu_period.MtuPeriod()  # noqa: E501
        if include_optional :
            return MtuPeriod(
                from_mtu_start = '2022-01-04T10:00Z', 
                to_mtu_end = '2022-01-04T11:00Z'
            )
        else :
            return MtuPeriod(
                from_mtu_start = '2022-01-04T10:00Z',
                to_mtu_end = '2022-01-04T11:00Z',
        )
        """

    def testMtuPeriod(self):
        """Test MtuPeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
