# coding: utf-8

"""
    Empire - Platform API

    OpenAPI specification for the Platform REST API of Empire  **System Time:** Europe/Amsterdam  **General data formats:**   * _capacity values_ => kW (integers)   * _dates and local times_ => System Time   * _currencies_ => EUR   # noqa: E501

    The version of the OpenAPI document: 0.179.13
    Contact: britned.info@britned.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import empire_platform_api_public_client
from empire_platform_api_public_client.api.public_allocated_auction_api import PublicAllocatedAuctionApi  # noqa: E501
from empire_platform_api_public_client.rest import ApiException


class TestPublicAllocatedAuctionApi(unittest.TestCase):
    """PublicAllocatedAuctionApi unit test stubs"""

    def setUp(self):
        self.api = empire_platform_api_public_client.api.public_allocated_auction_api.PublicAllocatedAuctionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_public_aggregated_allocated_auctions(self):
        """Test case for get_public_aggregated_allocated_auctions

        """
        pass

    def test_get_public_allocated_auctions(self):
        """Test case for get_public_allocated_auctions

        """
        pass


if __name__ == '__main__':
    unittest.main()
