# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dydxprotocol/clob/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from dydxprotocol.clob import order_pb2 as dydxprotocol_dot_clob_dot_order__pb2
from dydxprotocol.clob import order_removals_pb2 as dydxprotocol_dot_clob_dot_order__removals__pb2
from dydxprotocol.clob import matches_pb2 as dydxprotocol_dot_clob_dot_matches__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64ydxprotocol/clob/tx.proto\x12\x11\x64ydxprotocol.clob\x1a\x14gogoproto/gogo.proto\x1a\x1d\x64ydxprotocol/clob/order.proto\x1a&dydxprotocol/clob/order_removals.proto\x1a\x1f\x64ydxprotocol/clob/matches.proto\"X\n\x15MsgProposedOperations\x12?\n\x10operations_queue\x18\x01 \x03(\x0b\x32\x1f.dydxprotocol.clob.OperationRawB\x04\xc8\xde\x1f\x00\"\x1f\n\x1dMsgProposedOperationsResponse\">\n\rMsgPlaceOrder\x12-\n\x05order\x18\x01 \x01(\x0b\x32\x18.dydxprotocol.clob.OrderB\x04\xc8\xde\x1f\x00\"\x17\n\x15MsgPlaceOrderResponse\"\x8f\x01\n\x0eMsgCancelOrder\x12\x32\n\x08order_id\x18\x01 \x01(\x0b\x32\x1a.dydxprotocol.clob.OrderIdB\x04\xc8\xde\x1f\x00\x12\x18\n\x0egood_til_block\x18\x02 \x01(\rH\x00\x12\x1d\n\x13good_til_block_time\x18\x03 \x01(\x07H\x00\x42\x10\n\x0egood_til_oneof\"\x18\n\x16MsgCancelOrderResponse\"\xaa\x01\n\x0cOperationRaw\x12-\n\x05match\x18\x01 \x01(\x0b\x32\x1c.dydxprotocol.clob.ClobMatchH\x00\x12$\n\x1ashort_term_order_placement\x18\x02 \x01(\x0cH\x00\x12\x38\n\rorder_removal\x18\x03 \x01(\x0b\x32\x1f.dydxprotocol.clob.OrderRemovalH\x00\x42\x0b\n\toperation2\xae\x02\n\x03Msg\x12p\n\x12ProposedOperations\x12(.dydxprotocol.clob.MsgProposedOperations\x1a\x30.dydxprotocol.clob.MsgProposedOperationsResponse\x12X\n\nPlaceOrder\x12 .dydxprotocol.clob.MsgPlaceOrder\x1a(.dydxprotocol.clob.MsgPlaceOrderResponse\x12[\n\x0b\x43\x61ncelOrder\x12!.dydxprotocol.clob.MsgCancelOrder\x1a).dydxprotocol.clob.MsgCancelOrderResponseB)Z\'github.com/dydxprotocol/v4/x/clob/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dydxprotocol.clob.tx_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/dydxprotocol/v4/x/clob/types'
  _MSGPROPOSEDOPERATIONS.fields_by_name['operations_queue']._options = None
  _MSGPROPOSEDOPERATIONS.fields_by_name['operations_queue']._serialized_options = b'\310\336\037\000'
  _MSGPLACEORDER.fields_by_name['order']._options = None
  _MSGPLACEORDER.fields_by_name['order']._serialized_options = b'\310\336\037\000'
  _MSGCANCELORDER.fields_by_name['order_id']._options = None
  _MSGCANCELORDER.fields_by_name['order_id']._serialized_options = b'\310\336\037\000'
  _globals['_MSGPROPOSEDOPERATIONS']._serialized_start=175
  _globals['_MSGPROPOSEDOPERATIONS']._serialized_end=263
  _globals['_MSGPROPOSEDOPERATIONSRESPONSE']._serialized_start=265
  _globals['_MSGPROPOSEDOPERATIONSRESPONSE']._serialized_end=296
  _globals['_MSGPLACEORDER']._serialized_start=298
  _globals['_MSGPLACEORDER']._serialized_end=360
  _globals['_MSGPLACEORDERRESPONSE']._serialized_start=362
  _globals['_MSGPLACEORDERRESPONSE']._serialized_end=385
  _globals['_MSGCANCELORDER']._serialized_start=388
  _globals['_MSGCANCELORDER']._serialized_end=531
  _globals['_MSGCANCELORDERRESPONSE']._serialized_start=533
  _globals['_MSGCANCELORDERRESPONSE']._serialized_end=557
  _globals['_OPERATIONRAW']._serialized_start=560
  _globals['_OPERATIONRAW']._serialized_end=730
  _globals['_MSG']._serialized_start=733
  _globals['_MSG']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
